### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ghost** [klederson/angular-masonry-directive#16]
For some reason it doesn't work even tho I included it as you explained.
![screen shot 2015-03-05 at 14 51 08](https://cloud.githubusercontent.com/assets/8222282/6505936/36b4c522-c347-11e4-9d4f-dee91b7a995e.png)
![screen shot 2015-03-05 at 14 51 31](https://cloud.githubusercontent.com/assets/8222282/6505935/36b1d9e8-c347-11e4-9527-39abe196aef4.png)

**Comment by GrayYoung** [comment]
I have a same problem, how did you resolve the issue?

**Comment by tafid** [comment]
+1
