### ISSUE TITLE
Docs need updating

### ISSUE THREAD

**Issue by esslamben** [klederson/angular-masonry-directive#36]
The documentation doesn't include the fact that it requires the masonry js file and the imagesloaded js file which is no longer including with masonry. Also your example has a class selected .title but this is not included on the masonry-tile div.

**Comment by Esslamb** [comment]
<div masonry='{ "transitionDuration" : "0.4s" , "itemSelector" : ".tile"}'>
                            <div masonry-tile ng-repeat="post in tempList" class="tile">
                                 <img src="http://unsplash.it/250/150?random" alt="Latest News">
                            </div>
                        </div>
